// <auto-generated />
namespace JoshDevenyi_PokemonPassionProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewPokemonTypeTable_WillHoldPokemonTypesInsteadOfTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewPokemonTypeTable_WillHoldPokemonTypesInsteadOfTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "202202040020216_NewPokemonTypeTable_WillHoldPokemonTypesInsteadOfTypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
