// <auto-generated />
namespace JoshDevenyi_PokemonPassionProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class pokemonprimarytype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pokemonprimarytype));
        
        string IMigrationMetadata.Id
        {
            get { return "202201262016306_pokemon-primary-type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
